name: Build FlowThroughTensors Shared Library

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y ninja-build cmake g++ libomp-dev

      - name: Build
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
          ninja

      - name: Upload Shared Library
        uses: actions/upload-artifact@v4
        with:
          name: FlowThroughTensors-linux
          path: build/libFlowThroughTensors.so

  build-macos:
    name: Build on macOS
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install ninja libomp

      - name: Build
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
          ninja

      - name: Upload Shared Library
        uses: actions/upload-artifact@v4
        with:
          name: FlowThroughTensors-macos
          path: build/libFlowThroughTensors.dylib

  build-macos-arm:
    name: Build on macOS ARM
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update
          brew install ninja libomp

      - name: Build
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..
          ninja

      - name: Upload Shared Library
        uses: actions/upload-artifact@v4
        with:
          name: FlowThroughTensors-macos-arm
          path: build/libFlowThroughTensors_arm.dylib

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release

      - name: Upload Shared Library
        uses: actions/upload-artifact@v4
        with:
          name: FlowThroughTensors-windows
          path: build/FlowThroughTensors.dll
